MARKS = {
    "Audi": "/cars/audi/",
    "BAIC": "/cars/baic/",
    "BMW": "/cars/bmw/",
    "BYD": "/cars/byd/",
    "Bentley": "/cars/bentley/",
    "Cadillac": "/cars/cadillac/",
    "Changan": "/cars/changan/",
    "Chery": "/cars/chery/",
    "Chevrolet": "/cars/chevrolet/",
    "Chrysler": "/cars/chrysler/",
    "Citroen": "/cars/citroen/",
    "Daewoo": "/cars/daewoo/",
    "Daihatsu": "/cars/daihatsu/",
    "Datsun": "/cars/datsun/",
    "Dodge": "/cars/dodge/",
    "EXEED": "/cars/exeed/",
    "FAW": "/cars/faw/",
    "Fiat": "/cars/fiat/",
    "Ford": "/cars/ford/",
    "Foton": "/cars/foton/",
    "GMC": "/cars/gmc/",
    "Geely": "/cars/geely/",
    "Genesis": "/cars/genesis/",
    "Great Wall": "/cars/great-wall/",
    "Haval": "/cars/haval/",
    "Honda": "/cars/honda/",
    "Hummer": "/cars/hummer/",
    "Hyundai": "/cars/hyundai/",
    "Infiniti": "/cars/infiniti/",
    "Isuzu": "/cars/isuzu/",
    "JAC": "/cars/jac/",
    "Jaguar": "/cars/jaguar/",
    "Jeep": "/cars/jeep/",
    "Kia": "/cars/kia/",
    "Land Rover": "/cars/land-rover/",
    "Lexus": "/cars/lexus/",
    "Lifan": "/cars/lifan/",
    "Lincoln": "/cars/lincoln/",
    "MG": "/cars/mg/",
    "Mazda": "/cars/mazda/",
    "Mercedes-Benz": "/cars/mercedes-benz/",
    "Mercedes-Maybach": "/cars/mercedes-maybach/",
    "Mini": "/cars/mini/",
    "Mitsubishi": "/cars/mitsubishi/",
    "Nissan": "/cars/nissan/",
    "Opel": "/cars/opel/",
    "Peugeot": "/cars/peugeot/",
    "Pontiac": "/cars/pontiac/",
    "Porsche": "/cars/porsche/",
    "Ravon": "/cars/ravon/",
    "Renault": "/cars/renault/",
    "Renault Samsung": "/cars/samsung/",
    "Rover": "/cars/rover/",
    "Saab": "/cars/saab/",
    "Seat": "/cars/seat/",
    "Skoda": "/cars/skoda/",
    "SsangYong": "/cars/ssang-yong/",
    "Subaru": "/cars/subaru/",
    "Suzuki": "/cars/suzuki/",
    "Tesla": "/cars/tesla/",
    "Toyota": "/cars/toyota/",
    "Volkswagen": "/cars/volkswagen/",
    "Volvo": "/cars/volvo/",
    "Zeekr": "/cars/zeekr/",
    # "ВАЗ (Lada)": "/cars/vaz/",
    # "ГАЗ": "/cars/gaz/",
    # "ЗАЗ": "/cars/zaz/",
    # "ИЖ": "/cars/ij/",
    # "Москвич": "/cars/moskvich/",
    # "Ретро-автомобили": "/cars/retro-automobiles/",
    # "УАЗ": "/cars/uaz/"
}